### ISSUE TITLE
Forwarding to channels

### ISSUE THREAD

**Issue by orangebutblue** [xates/tg-channel-watcher#8]
Is it possible to forward the messages to Telegram-channels, instead of forwarding it to "me"?

I've set set the "recipient" to my channel chat-id (which is a negative number)

However, I always keep getting this error:
```
Traceback (most recent call last):
  File "./main.py", line 41, in <module>
    fallback="me").strip())
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 2439, in get_input_entity
    return utils.get_input_peer(self._get_entity_from_string(peer))
  File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 2406, in _get_entity_from_string
    'Cannot turn "{}" into any entity (user or chat)'.format(string)
TypeError: Cannot turn "-10012xxxxxxxx" into any entity (user or chat)
```

**Comment by xates** [comment]
Use a username (or an invite link for private channels), just like in the list of channels to watch

**Comment by orangebutblue** [comment]
I see. Great, thanks!

**Comment by xates** [comment]
You're welcome ;)
